name: build

on:
  pull_request:
    branches:
    - "**"
  push:
    branches:
    - main

env:
  MINIO_URL: http://minio:9000
  MINIO_ROOT_USER: ${{ secrets.MINIO_ROOT_USER }}
  MINIO_ROOT_PASSWORD: ${{ secrets.MINIO_ROOT_PASSWORD }}
  MINIO_REGION_NAME: berttopic
  MINIO_BUCKET_NAME: default_bucket
  MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
  MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
  DOCKER_BUILDKIT: 1
  POSTGRES_HOST: db
  POSTGRES_PORT: 5432
  POSTGRES_DB: bertopic
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  IMAGE_TAG: shkaolin/bertopic-as-service:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          tags: ${{ env.IMAGE_TAG }}
          cache-from: type=gha
      - name: Start services
        run: |
          make up
      - name: Run code checks
        run: |
          docker-compose run --rm --no-deps bertopic make check-code
      - name: Run integration tests
        run: |
          make test
